//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AtikIslem
    {
        public int TanimID { get; set; }
        public string Plaka { get; set; }
        public string Ruhsat { get; set; }
        public string Adres { get; set; }
        public string Tur { get; set; }
        public string Kurum { get; set; }
        public string TAd { get; set; }
        public string TSoyad { get; set; }
        public string TTel { get; set; }
        public string ITarih { get; set; }
    }
}
