//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class IletisimBilgi
    {
        public int IletisimID { get; set; }
        public string Il { get; set; }
        public string Ilce { get; set; }
        public string Bucak_Koy_ { get; set; }
        public string Mahalle { get; set; }
        public string CSBM { get; set; }
        public string DisKapi { get; set; }
        public string IcKapi { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public string E_posta { get; set; }
    }
}
