//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kompost
    {
        public int KompostID { get; set; }
        public Nullable<System.DateTime> BeslemeTarihi { get; set; }
        public Nullable<System.DateTime> EldeEtmeTarihi { get; set; }
        public string KompostYöntem { get; set; }
        public Nullable<int> BMiktar { get; set; }
        public Nullable<int> EMiktar { get; set; }
        public Nullable<int> Kapasite { get; set; }
    
        public virtual FaliyetUst FaliyetUst { get; set; }
    }
}
