//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class KullaniciKyt
    {
        public int KullaniciID { get; set; }
        public string Tc { get; set; }
        public string Il { get; set; }
        public string Ilce { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Tel { get; set; }
        public string Eposta { get; set; }
        public string Sifre { get; set; }
        public string SifreTekrar { get; set; }
    }
}
