//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AtikUygulamaEntities : DbContext
    {
        public AtikUygulamaEntities()
            : base("name=AtikUygulamaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AtikEkle> AtikEkle { get; set; }
        public virtual DbSet<AtikIslem> AtikIslem { get; set; }
        public virtual DbSet<KullaniciKyt> KullaniciKyt { get; set; }
    }
}
