//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TesisBilgisi
    {
        public int TesisID { get; set; }
        public string FirmaAd { get; set; }
        public string TesisAd { get; set; }
        public Nullable<int> VergiNo { get; set; }
        public string Il { get; set; }
        public string Ilce { get; set; }
        public string Adres { get; set; }
        public string KurumTur { get; set; }
        public Nullable<int> YillikAtikMiktar { get; set; }
        public string YetkiliAdSoyad { get; set; }
        public string YetkiliTel { get; set; }
        public string YetkiliE_posta { get; set; }
        public Nullable<System.DateTime> KayitTarih { get; set; }
        public Nullable<int> KatSayisi { get; set; }
        public string Yemekhane { get; set; }
        public string YesilAlan { get; set; }
        public string Revir { get; set; }
        public string Aciklama { get; set; }
    }
}
