//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToplananAtik
    {
        public int AtikID { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string AtikTur { get; set; }
        public Nullable<int> Miktar { get; set; }
        public Nullable<System.DateTime> TeslimTarih { get; set; }
        public byte[] TeslimBelgesi { get; set; }
    
        public virtual FaliyetUst FaliyetUst { get; set; }
    }
}
