//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class VergiGiris
    {
        public int VergiID { get; set; }
        public string HesapTipi { get; set; }
        public Nullable<int> VergiNo { get; set; }
        public string VergiDairesiIl { get; set; }
        public string VergiDairesi { get; set; }
    }
}
