//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class YerlestirilenEkipman
    {
        public int EkipmanID { get; set; }
        public string EkipTur { get; set; }
        public string Miktar { get; set; }
    
        public virtual FaliyetUst FaliyetUst { get; set; }
    }
}
