//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Proje.Web
{
    public partial class AtikKayit
    {
        protected global::System.Web.UI.WebControls.TextBox TxtAdres;
        protected global::System.Web.UI.WebControls.TextBox TxtTur;
        protected global::System.Web.UI.WebControls.TextBox TxtIslem;
        protected global::System.Web.UI.WebControls.Label lblUyari1;
    }
}
