//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Proje.Web
{
    public partial class AtikTanim
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.TextBox TxtRuhsat;
        
        protected global::System.Web.UI.WebControls.TextBox TxtPlaka;
        protected global::System.Web.UI.WebControls.TextBox TasıyıcıAd;
        protected global::System.Web.UI.WebControls.TextBox TasıyıcıSoyad;
        protected global::System.Web.UI.WebControls.TextBox TasıyıcıTel;
        protected global::System.Web.UI.WebControls.TextBox IslemTarihi;
        protected global::System.Web.UI.WebControls.DropDownList dllAdres;
        protected global::System.Web.UI.WebControls.DropDownList dllTur;
        protected global::System.Web.UI.WebControls.DropDownList dllKurum;
        protected global::System.Web.UI.WebControls.Label lblUyari1;
        protected global::System.Web.UI.WebControls.Button btnGuncelle;
        protected global::System.Web.UI.WebControls.Button btnSil;
    }
}
