//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.Web
{


    public partial class WebForm1
    {

        /// <summary>
        /// button1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button button1;

        /// <summary>
        /// kullanicilar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.GridView gvUyeler;
        protected global::System.Web.UI.WebControls.TextBox Eposta;
        protected global::System.Web.UI.WebControls.TextBox Ad;
        protected global::System.Web.UI.WebControls.TextBox Soyad;
        protected global::System.Web.UI.WebControls.TextBox Tel;
        protected global::System.Web.UI.WebControls.TextBox Sifre;
        protected global::System.Web.UI.WebControls.TextBox Tc;
        protected global::System.Web.UI.WebControls.TextBox Il;
        protected global::System.Web.UI.WebControls.TextBox Ilce;
        protected global::System.Web.UI.WebControls.TextBox ID;

        protected global::System.Web.UI.WebControls.SqlDataSource dsUyeler;
        protected global::System.Web.UI.WebControls.Label lblUyari;
        protected global::System.Web.UI.WebControls.Button btnKaydet;
        protected global::System.Web.UI.WebControls.Button btnSil;
        protected global::System.Web.UI.WebControls.Button Yeni;
    }
}
